#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"

#include "audio_hw.h"
#include "gpio_config.h"

static i2s_chan_handle_t tx_handle;

static float s_notes_freq[NOTE_MAX][OCTAVE_MAX];
DRAM_ATTR uint16_t sending_buffer[SAMPLES_BUFFER_SIZE];

void audio_send(float * buffer)
{
    esp_err_t err;
    size_t sent_data_size = 0;

    for(int i = 0; i < SAMPLES_BUFFER_SIZE; i++)
    {
        sending_buffer[i] = (uint16_t)buffer[i];
    }

    err = i2s_channel_write(tx_handle, sending_buffer, sizeof(int16_t) * SAMPLES_BUFFER_SIZE , &sent_data_size, 1000);
}

void i2s_init()
{
    //i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
    i2s_chan_config_t chan_cfg =
    {
        .auto_clear = false,
        .dma_desc_num = 6,
        .dma_frame_num = DMA_FRAME_NUM,
        .id = I2S_NUM_0,
        .role = I2S_ROLE_MASTER
    };
    /* Allocate a new tx channel and get the handle of this channel */
    i2s_new_channel(&chan_cfg, &tx_handle, NULL);
    /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
    * They can help to specify the slot and clock configurations for initialization or updating */
    i2s_std_config_t std_cfg = {
        .clk_cfg = 
        {
            .clk_src = I2S_CLK_SRC_DEFAULT,
            .mclk_multiple = I2S_MCLK_MULTIPLE_256,
            .sample_rate_hz = SAMPLE_RATE,
        },
        .slot_cfg = 
        {
            .bit_shift = false,
            .data_bit_width = I2S_DATA_BIT_WIDTH_16BIT,
            .slot_bit_width = I2S_SLOT_BIT_WIDTH_16BIT,
            .slot_mask = I2S_STD_SLOT_BOTH,
            .slot_mode = I2S_SLOT_MODE_STEREO,
            .ws_pol = false,
            .ws_width = I2S_DATA_BIT_WIDTH_16BIT,
        },
        .gpio_cfg = {
            .mclk = I2S_GPIO_UNUSED,
            .bclk = I2S_OUT_BCLK,
            .ws = I2S_OUT_WS,
            .dout = I2S_OUT_DO,
            .din = I2S_GPIO_UNUSED,
            .invert_flags = {
                .mclk_inv = false,
                .bclk_inv = false,
                .ws_inv = false,
            },
        },
    };

    i2s_channel_init_std_mode(tx_handle, &std_cfg);
    i2s_channel_enable(tx_handle);
}


float get_note_freq(audio_note_e note, audio_octaves_e octave)
{
    return s_notes_freq[note][octave];
}
